services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        - "PORT=8080"
  curtain:
    container_name: curtain
    build:
      context: .
      dockerfile: Dockerfile.device
      args:
        - "PORT=8080"
        - "SERVER_URL=http://server:8080"
        - "DEVICE_TYPE=curtain"
  air-conditioner:
    container_name: air-conditioner
    build:
      context: .
      dockerfile: Dockerfile.device
      args:
        - "PORT=8080"
        - "SERVER_URL=http://server:8080"
        - "DEVICE_TYPE=air-conditioner"
  tv:
    container_name: tv
    build:
      context: .
      dockerfile: Dockerfile.device
      args:
        - "PORT=8080"
        - "SERVER_URL=http://server:8080"
        - "DEVICE_TYPE=tv"
  sound-system:
    container_name: sound-system
    build:
      context: .
      dockerfile: Dockerfile.device
      args:
        - "PORT=8080"
        - "SERVER_URL=http://server:8080"
        - "DEVICE_TYPE=sound-system"
  light:
    container_name: light
    build:
      context: .
      dockerfile: Dockerfile.device
      args:
        - "PORT=8080"
        - "SERVER_URL=http://server:8080"
        - "DEVICE_TYPE=light"
